classdef TeachingModuleShowcaseSupportRegressionBasics
    methods (Static)
        function result = baselineDemo(choice)
            arguments
                choice (1,1) string {mustBeMember(choice,["Housing prices","Sample fit challenge","Ventilator practice"])}
            end

            data = TeachingModuleShowcaseSupportRegressionBasics.makeBaselineScenario(choice);
            mdl = fitlm(data.x,data.y);

            xGrid = linspace(min(data.x),max(data.x),200)';
            fitGrid = predict(mdl,xGrid);
            fittedValues = predict(mdl,data.x);
            residuals = data.y - fittedValues;
            sse = sum(residuals.^2);

            summary = table( ...
                data.Label,sse,mdl.Coefficients.Estimate(2),mdl.Coefficients.Estimate(1), ...
                'VariableNames',["Scenario","SSE","Slope","Intercept"]);

            result = struct( ...
                "Label",data.Label, ...
                "x",data.x, ...
                "y",data.y, ...
                "xGrid",xGrid, ...
                "FitGrid",fitGrid, ...
                "FittedValues",fittedValues, ...
                "Residuals",residuals, ...
                "SSE",sse, ...
                "XLabel",data.XLabel, ...
                "YLabel",data.YLabel, ...
                "Summary",summary, ...
                "TeachingNote",data.TeachingNote);
        end

        function result = linearityAssumptionDemo(choice)
            arguments
                choice (1,1) string {mustBeMember(choice,["House prices with amenities","Heat exchanger soft sensor","DC power practice"])}
            end

            data = TeachingModuleShowcaseSupportRegressionBasics.makeMultipleScenario(choice);
            [X,~] = TeachingModuleShowcaseSupportRegressionBasics.fullPredictorMatrix(data);

            mdl1 = fitlm(data.x1,data.y);
            mdl2 = fitlm(data.x2,data.y);
            fullMdl = fitlm(X,data.y);

            x1Grid = linspace(min(data.x1),max(data.x1),200)';
            x2Grid = linspace(min(data.x2),max(data.x2),200)';
            y1Fit = predict(mdl1,x1Grid);
            y2Fit = predict(mdl2,x2Grid);
            fittedValues = predict(fullMdl,X);
            residuals = data.y - fittedValues;

            summary = table( ...
                [data.Predictor1Name; data.Predictor2Name; "Full model"], ...
                ["Simple R-squared"; "Simple R-squared"; "Adjusted R-squared"], ...
                [mdl1.Rsquared.Ordinary; mdl2.Rsquared.Ordinary; fullMdl.Rsquared.Adjusted], ...
                ["Look for an approximately straight trend, not a pronounced curve."; "Look for an approximately straight trend, not a pronounced curve."; "Residuals should stay near zero with no curve, drift, clustering, or fan shape."], ...
                'VariableNames',["Diagnostic view","Metric","Value","What to look for"]);

            if isfield(data,"x3")
                displayNote = "The compact preview plots the first two predictors, while the full-model check is computed from the model that also includes " + data.Predictor3Name + ". Treat the scatter plots as a first screen: if the full-model residuals still show structure, revise the model before interpreting the coefficients.";
            else
                displayNote = "The scatter plots are a first screen, and the compact full-model check helps you decide whether the linear form still looks reasonable. If that check curves, drifts, clusters, or fans out, treat the model as provisional and revisit the model form.";
            end

            result = struct( ...
                "Label",data.Label, ...
                "x1",data.x1, ...
                "x2",data.x2, ...
                "y",data.y, ...
                "x1Grid",x1Grid, ...
                "x2Grid",x2Grid, ...
                "Y1Fit",y1Fit, ...
                "Y2Fit",y2Fit, ...
                "FittedValues",fittedValues, ...
                "Residuals",residuals, ...
                "X1Label",data.X1Label, ...
                "X2Label",data.X2Label, ...
                "YLabel",data.YLabel, ...
                "Summary",summary, ...
                "DisplayNote",displayNote, ...
                "TeachingNote",data.LinearityNote);
        end

        function result = multipleRegressionDemo(choice)
            arguments
                choice (1,1) string {mustBeMember(choice,["House prices with amenities","Heat exchanger soft sensor","DC power practice"])}
            end

            data = TeachingModuleShowcaseSupportRegressionBasics.makeMultipleScenario(choice);
            [X,predictorNames] = TeachingModuleShowcaseSupportRegressionBasics.fullPredictorMatrix(data);
            mdl = fitlm(X,data.y);

            fittedValues = predict(mdl,X);
            residuals = data.y - fittedValues;

            x1Grid = linspace(min(data.x1),max(data.x1),24);
            x2Grid = linspace(min(data.x2),max(data.x2),24);
            [X1Grid,X2Grid] = meshgrid(x1Grid,x2Grid);

            if isfield(data,"x3")
                heldValue = mean(data.x3);
                surfaceInput = [X1Grid(:) X2Grid(:) repmat(heldValue,numel(X1Grid),1)];
                surfaceNote = "Surface preview holds " + data.Predictor3Name + " at its mean value so you can read what the model predicts on the plane without losing the full-model fit.";
            else
                surfaceInput = [X1Grid(:) X2Grid(:)];
                surfaceNote = "Surface preview uses both predictors directly so you can compare the fitted plane to the data cloud before moving to the interactive app.";
            end

            surfaceFit = reshape(predict(mdl,surfaceInput),size(X1Grid));
            modelRMSE = mdl.RMSE;
            summary = table( ...
                data.Label,size(X,2),modelRMSE,mdl.Rsquared.Adjusted, ...
                'VariableNames',["Scenario","Number of predictors","Model RMSE","Adjusted R-squared"]);

            coefficientTable = table( ...
                ["(Intercept)"; predictorNames], ...
                mdl.Coefficients.Estimate, ...
                'VariableNames',["Coefficient","Estimate"]);

            result = struct( ...
                "Label",data.Label, ...
                "x1",data.x1, ...
                "x2",data.x2, ...
                "y",data.y, ...
                "X1Grid",X1Grid, ...
                "X2Grid",X2Grid, ...
                "SurfaceFit",surfaceFit, ...
                "FittedValues",fittedValues, ...
                "Residuals",residuals, ...
                "X1Label",data.X1Label, ...
                "X2Label",data.X2Label, ...
                "YLabel",data.YLabel, ...
                "Summary",summary, ...
                "CoefficientTable",coefficientTable, ...
                "ANOVATable",anova(mdl,"summary"), ...
                "SurfaceNote",surfaceNote, ...
                "TeachingNote",data.TeachingNote);
        end

        function launchInteractiveHouseModel()
            projectRoot = fileparts(mfilename("fullpath"));
            launchInteractiveHouseModelApp();
        end

        function result = curvilinearDemo(choice)
            arguments
                choice (1,1) string {mustBeMember(choice,["Crop yield and salinity","Battery lifetime decay","Bioreactor temperature"])}
            end

            scenario = TeachingModuleShowcaseSupportRegressionBasics.makeCurvilinearScenario(choice);
            x = scenario.x;
            y = scenario.y;
            xGrid = linspace(min(x),max(x),300)';

            switch scenario.Kind
                case "crop"
                    modelNames = ["Linear"; "Quadratic polynomial"; "Power law (linearized)"];
                    fitData = zeros(numel(x),3);
                    fitGrid = zeros(numel(xGrid),3);
                    teachingRead = [ ...
                        "Start on standard axes and ask whether a straight line is already adequate."; ...
                        "Compare the polynomial fit on standard axes and see whether it captures the visible curvature."; ...
                        "Use log-log axes, where both axes are logarithmic, to test whether a power law becomes straight enough to justify."];

                    linearCoeffs = polyfit(x,y,1);
                    quadCoeffs = polyfit(x,y,2);
                    mask = (x > 0) & (y > 0);
                    powerCoeffs = polyfit(log10(x(mask)),log10(y(mask)),1);
                    powerA = 10.^powerCoeffs(2);
                    powerB = powerCoeffs(1);

                    fitData(:,1) = polyval(linearCoeffs,x);
                    fitGrid(:,1) = polyval(linearCoeffs,xGrid);
                    fitData(:,2) = polyval(quadCoeffs,x);
                    fitGrid(:,2) = polyval(quadCoeffs,xGrid);
                    fitData(:,3) = powerA * x.^powerB;
                    fitGrid(:,3) = powerA * xGrid.^powerB;

                    primaryView = struct( ...
                        "Mode","plot", ...
                        "Title","Standard axes: polynomial shape", ...
                        "FitX",xGrid, ...
                        "FitY",fitGrid(:,2), ...
                        "FitName","Quadratic polynomial", ...
                        "XAxisLabel",scenario.XLabel, ...
                        "YAxisLabel",scenario.YLabel);

                    positiveGrid = xGrid > 0;
                    secondaryView = struct( ...
                        "Mode","loglog", ...
                        "Title","Log-log axes: power-law check", ...
                        "FitX",xGrid(positiveGrid), ...
                        "FitY",fitGrid(positiveGrid,3), ...
                        "FitName","Power-law fit", ...
                        "XAxisLabel",scenario.XLabel, ...
                        "YAxisLabel",scenario.YLabel);

                    axisNote = "Start on ordinary axes, compare the fit errors, then use log-log axes, where both axes are logarithmic, to test whether a power-law model becomes straight enough to justify. Choose the simplest model that captures the important pattern and stays easy to interpret.";

                case "battery"
                    modelNames = ["Linear"; "Exponential (linearized)"];
                    fitData = zeros(numel(x),2);
                    fitGrid = zeros(numel(xGrid),2);
                    teachingRead = [ ...
                        "Start on standard axes and check whether a straight line is already adequate."; ...
                        "Use semilogy axes, where only the response axis is logarithmic, to test whether exponential decay gives a more believable model."];

                    linearCoeffs = polyfit(x,y,1);
                    mask = y > 0;
                    expoCoeffs = polyfit(x(mask),log(y(mask)),1);
                    expoA = exp(expoCoeffs(2));
                    expoB = expoCoeffs(1);

                    fitData(:,1) = polyval(linearCoeffs,x);
                    fitGrid(:,1) = polyval(linearCoeffs,xGrid);
                    fitData(:,2) = expoA * exp(expoB * x);
                    fitGrid(:,2) = expoA * exp(expoB * xGrid);

                    primaryView = struct( ...
                        "Mode","plot", ...
                        "Title","Standard axes: curved decay", ...
                        "FitX",xGrid, ...
                        "FitY",fitGrid(:,2), ...
                        "FitName","Exponential fit", ...
                        "XAxisLabel",scenario.XLabel, ...
                        "YAxisLabel",scenario.YLabel);

                    secondaryView = struct( ...
                        "Mode","semilogy", ...
                        "Title","Semilogy axes: exponential check", ...
                        "FitX",xGrid, ...
                        "FitY",fitGrid(:,2), ...
                        "FitName","Exponential fit", ...
                        "XAxisLabel",scenario.XLabel, ...
                        "YAxisLabel",scenario.YLabel);

                    axisNote = "The table compares linear and exponential candidates, and the semilogy view shows whether the transformed response becomes straight enough to justify an exponential model without adding unnecessary complexity.";

                otherwise
                    modelNames = ["Linear"; "Quadratic polynomial"; "Cubic polynomial"];
                    fitData = zeros(numel(x),3);
                    fitGrid = zeros(numel(xGrid),3);
                    teachingRead = [ ...
                        "Start on standard axes and check whether a straight line is already adequate."; ...
                        "Use a quadratic fit on standard axes and see whether it captures the main bend."; ...
                        "Check a higher-order polynomial only if it adds visible structure you can still explain."];

                    poly1 = polyfit(x,y,1);
                    poly2 = polyfit(x,y,2);
                    poly3 = polyfit(x,y,3);

                    fitData(:,1) = polyval(poly1,x);
                    fitGrid(:,1) = polyval(poly1,xGrid);
                    fitData(:,2) = polyval(poly2,x);
                    fitGrid(:,2) = polyval(poly2,xGrid);
                    fitData(:,3) = polyval(poly3,x);
                    fitGrid(:,3) = polyval(poly3,xGrid);

                    primaryView = struct( ...
                        "Mode","plot", ...
                        "Title","Standard axes: polynomial behavior", ...
                        "FitX",xGrid, ...
                        "FitY",fitGrid(:,2), ...
                        "FitName","Quadratic polynomial", ...
                        "XAxisLabel",scenario.XLabel, ...
                        "YAxisLabel",scenario.YLabel);

                    secondaryView = struct( ...
                        "Mode","semilogy", ...
                        "Title","Semilogy check: still curved", ...
                        "FitX",xGrid, ...
                        "FitY",fitGrid(:,2), ...
                        "FitName","Quadratic polynomial", ...
                        "XAxisLabel",scenario.XLabel, ...
                        "YAxisLabel",scenario.YLabel);

                    axisNote = "Different axes are still worth checking, but this scenario stays most interpretable on standard axes with a polynomial fit, so prefer the polynomial model unless a transformed view becomes clearly straighter and easier to explain.";
            end

            rmse = zeros(numel(modelNames),1);
            for idx = 1:numel(modelNames)
                rmse(idx) = sqrt(mean((fitData(:,idx) - y).^2));
            end

            modelNamesCol = modelNames(:);
            teachingReadCol = teachingRead(1:numel(modelNames));
            teachingReadCol = teachingReadCol(:);
            summary = table(modelNamesCol,rmse(:),teachingReadCol,'VariableNames',["Model","RMSE","What to notice"]);
            [~,bestIdx] = min(rmse);

            result = struct( ...
                "Label",scenario.Label, ...
                "x",x, ...
                "y",y, ...
                "xGrid",xGrid, ...
                "FitGrid",fitGrid, ...
                "ModelNames",modelNames, ...
                "BestModel",modelNames(bestIdx), ...
                "Summary",summary, ...
                "PrimaryView",primaryView, ...
                "SecondaryView",secondaryView, ...
                "XLabel",scenario.XLabel, ...
                "YLabel",scenario.YLabel, ...
                "AxisNote",axisNote, ...
                "TeachingNote",scenario.TeachingNote);
        end

    end

    methods (Static, Access = private)
        function data = makeBaselineScenario(choice)
            switch choice
                case "Housing prices"
                    S = TeachingModuleShowcaseSupportRegressionBasics.loadData("LinearData.mat",["x","y"]);
                    data = struct( ...
                        "Label","Housing prices", ...
                        "x",S.x(:), ...
                        "y",S.y(:), ...
                        "XLabel","Area (sqft)", ...
                        "YLabel","Listed price (USD)", ...
                        "TeachingNote","SSE adds up the squared vertical residuals from the least-squares line, so the best-fit line is the one that drives total prediction error down. This mirrors the least-squares visualization in `LinearRegression.mlx` and creates a natural handoff into `TryRegression.mlx`.");

                case "Sample fit challenge"
                    S = TeachingModuleShowcaseSupportRegressionBasics.loadData("SampleData.mat",["x","y"]);
                    data = struct( ...
                        "Label","Sample fit challenge", ...
                        "x",S.x(:), ...
                        "y",S.y(:), ...
                        "XLabel","$x$", ...
                        "YLabel","$y$", ...
                        "TeachingNote","Use SSE to compare candidate lines and then show why the least-squares line wins by minimizing the total squared prediction error rather than by making every residual zero.");

                otherwise
                    S = TeachingModuleShowcaseSupportRegressionBasics.loadData("Ventilator.mat",["t","V"]);
                    data = struct( ...
                        "Label","Ventilator practice preview", ...
                        "x",S.t(:), ...
                        "y",S.V(:), ...
                        "XLabel","Time (s)", ...
                        "YLabel","Condensed water (mL)", ...
                        "TeachingNote","This connects the showcase directly to `TryRegression.mlx`, where students can compare lines with SSE and then fit and use the least-squares model themselves.");
            end
        end

        function data = makeMultipleScenario(choice)
            switch choice
                case "House prices with amenities"
                    S = TeachingModuleShowcaseSupportRegressionBasics.loadData("MultivariateData.mat",["x1","x2","y"]);
                    data = struct( ...
                        "Label","House prices with amenities", ...
                        "x1",S.x1(:), ...
                        "x2",S.x2(:), ...
                        "y",S.y(:), ...
                        "Predictor1Name","Additional features", ...
                        "Predictor2Name","Area", ...
                        "X1Label","Additional features", ...
                        "X2Label","Area (sqft)", ...
                        "YLabel","Listed price (USD)", ...
                        "LinearityNote","This preview mirrors the housing diagnostics path in `MultipleRegression.mlx`: use the predictor views as a first screen, then decide with the residual plot whether the linear model is still a reasonable starting point.", ...
                        "TeachingNote","This housing scenario leads directly into the Generate a Plane of Coefficients app in `MultipleRegression.mlx`. Here, Model RMSE summarizes the typical prediction error in listed-price units, and Adjusted R-squared summarizes explained variation after accounting for the number of predictors. The fitted plane shows what the model believes across combinations of inputs.");

                case "Heat exchanger soft sensor"
                    [mDot,dT,QkW] = TeachingModuleShowcaseSupportRegressionBasics.makeHeatExchangerData();
                    data = struct( ...
                        "Label","Heat exchanger soft sensor", ...
                        "x1",mDot, ...
                        "x2",dT, ...
                        "y",QkW, ...
                        "Predictor1Name","Mass flow rate", ...
                        "Predictor2Name","Temperature change", ...
                        "X1Label","$\dot{m}$ (kg/s)", ...
                        "X2Label","$\Delta T$ (degC)", ...
                        "YLabel","Heat duty (kW)", ...
                        "LinearityNote","This is the engineering-facing assumptions story from `MultipleRegression.mlx`: check the predictor views first, then treat the model as a reasonable starting point only if the residuals stay pattern-free rather than drifting with order or fitted value.", ...
                        "TeachingNote","This example makes the case that regression is being used as a modeling tool tied to measured engineering variables. The point is not only to compute coefficients, but to judge whether the fitted model is believable.");

                otherwise
                    S = TeachingModuleShowcaseSupportRegressionBasics.loadData("DCPowerData.mat",["TrafficLoad","ActiveModules","AmbientTemp","DCPower"]);
                    data = struct( ...
                        "Label","DC power practice preview", ...
                        "x1",S.TrafficLoad(:), ...
                        "x2",S.ActiveModules(:), ...
                        "x3",S.AmbientTemp(:), ...
                        "y",S.DCPower(:), ...
                        "Predictor1Name","Traffic load", ...
                        "Predictor2Name","Active modules", ...
                        "Predictor3Name","Ambient temperature", ...
                        "X1Label","Traffic load", ...
                        "X2Label","Active modules", ...
                        "X3Label","Ambient temperature (degC)", ...
                        "YLabel","DC power (W)", ...
                        "LinearityNote","This points to the practice path in `TryMultiple.mlx`, where students fit a three-predictor model and use residuals to decide whether the linear form stays reasonable without using the house-model app.", ...
                        "TeachingNote","This practice-aligned example shows what students type after the teaching live script: fit the model, inspect ANOVA, and work through residual diagnostics in `TryMultiple.mlx` before deciding how much to trust the linear fit.");
            end
        end

        function scenario = makeCurvilinearScenario(choice)
            switch choice
                case "Crop yield and salinity"
                    S = TeachingModuleShowcaseSupportRegressionBasics.loadData("NonlinearData.mat",["x","y"]);
                    scenario = struct( ...
                        "Kind","crop", ...
                        "Label","Crop yield and salinity", ...
                        "x",S.x(:), ...
                        "y",S.y(:), ...
                        "XLabel","Salinity in the root zone (dS/m)", ...
                        "YLabel","Crop yield", ...
                        "TeachingNote","This preview stays close to `CurvilinearRegression.mlx` by comparing a straight line, a polynomial option, and a linearizable nonlinear alternative, meaning a curved relationship that becomes easier to fit after a transform. The goal is to decide when curvature matters enough to change the model form.");

                case "Battery lifetime decay"
                    S = TeachingModuleShowcaseSupportRegressionBasics.loadData("BatterySOH.mat",["t","SOH"]);
                    scenario = struct( ...
                        "Kind","battery", ...
                        "Label","Battery lifetime decay", ...
                        "x",S.t(:), ...
                        "y",S.SOH(:), ...
                        "XLabel","Time", ...
                        "YLabel","State of health", ...
                        "TeachingNote","This preview connects to `TryCurvilinear.mlx`, where students linearize a nonlinear relationship and then convert predictions back to the original units. It reinforces that lower error helps only when the transformed model still makes sense to explain.");

                otherwise
                    S = TeachingModuleShowcaseSupportRegressionBasics.loadData("Bioreactor.mat",["Temp","Prod"]);
                    scenario = struct( ...
                        "Kind","bioreactor", ...
                        "Label","Bioreactor temperature", ...
                        "x",S.Temp(:), ...
                        "y",S.Prod(:), ...
                        "XLabel","Bioreactor temperature (degC)", ...
                        "YLabel","Product titer", ...
                        "TeachingNote","This preview points naturally to `TryCurvilinearPolynomial.mlx`, where polynomial regression becomes a student-facing workflow. It reinforces choosing the simplest curved model that captures the important pattern.");
            end
        end

        function S = loadData(filename,variables)
            proj = currentProject;

            fullName = fullfile(proj.RootFolder,"Data",filename);

            if ~isfile(fullName)
                error("Could not find data file: %s",fullName)
            end

            vars = cellstr(variables);
            S = load(fullName,vars{:});
        end
        function [X,predictorNames] = fullPredictorMatrix(data)
            X = [data.x1 data.x2];
            predictorNames = [data.Predictor1Name; data.Predictor2Name];

            if isfield(data,"x3")
                X = [X data.x3];
                predictorNames(end+1,1) = data.Predictor3Name;
            end
        end

        function [mDot,dT,QkW] = makeHeatExchangerData()
            rng(11,"twister")
            n = 121;
            mDot = 1.30 + 0.22 * randn(n,1);
            dT = 20.0 + 2.60 * randn(n,1);
            mDot = max(0.8,min(mDot,1.9));
            dT = max(12,min(dT,28));
            QkW = 5 + 65 * mDot + 12 * dT + 0.9 * randn(n,1);
        end
    end
end
function fig = launchInteractiveHouseModelApp
% launchInteractiveHouseModelApp Open the regression-basics house-model app.

try
    projectRoot = fileparts(fileparts(mfilename("fullpath")));
    dataFile = fullfile(projectRoot,"Data","MultivariateData.mat");
    S = load(dataFile,"x1","x2","y");
    x1 = S.x1;
    x2 = S.x2;
    y = S.y;
catch
    rng(42,"twister")
    n = 100;
    x1 = 1 + 4*rand(n,1);
    x2 = 500 + 2000*rand(n,1);
    truea1 = 7500;
    truea2 = 250;
    truea0 = 6000;
    y = truea1*x1 + truea2*x2 + truea0 + 20000*randn(n,1);
end

X = [ones(length(x1),1),x1,x2];
optimalCoeffs = X \ y;
a0Opt = optimalCoeffs(1);
a1Opt = optimalCoeffs(2);
a2Opt = optimalCoeffs(3);
optimalSSE = sum((y - (a1Opt*x1 + a2Opt*x2 + a0Opt)).^2);
baselineSSE = sum((y - mean(y)).^2);

a1Limits = expandSliderLimits([1000 150000],a1Opt,1000);
a2Limits = expandSliderLimits([5 200],a2Opt,25);
a0Limits = expandSliderLimits([5000 150000],a0Opt,5000);
initialView = [-150 25];
maxPoorFitTries = 50;

[a1,a2,a0] = randomPoorCoefficients();
referenceSSE = baselineSSE;
theme = houseModelTheme();

fig = uifigure(Name="Interactive House Price Model - 3D Linear Regression", ...
    Position=[100 100 1200 700]);

mainGrid = uigridlayout(fig,[2,3]);
mainGrid.ColumnWidth = {300,"1x",250};
mainGrid.RowHeight = {"1x",80};

leftPanel = uipanel(mainGrid,Title="Model Parameters",FontWeight="bold");
leftPanel.Layout.Row = 1;
leftPanel.Layout.Column = 1;

controlGrid = uigridlayout(leftPanel,[12,1]);
controlGrid.RowHeight = {"fit","fit","fit","fit","fit","fit","fit","fit","fit","fit","fit","1x"};
controlGrid.Padding = [15 15 15 15];
controlGrid.RowSpacing = 8;

instructLabel = uilabel(controlGrid, ...
    Text=(" Adjust the sliders to find the best linear model!" + newline + ...
    "Try to minimize the residuals."), ...
    FontWeight="bold",FontColor=theme.InstructionColor, ...
    WordWrap="on");
instructLabel.Layout.Row = 1;

a1TitleLabel = uilabel(controlGrid,Text="Price per Additional Feature", ...
    FontWeight="bold",FontColor=theme.FeatureColor);
a1TitleLabel.Layout.Row = 2;
a1ValueLabel = uilabel(controlGrid,Text="$" + formatWholeNumber(a1) + " per feature", ...
    FontColor=theme.FeatureValueColor);
a1ValueLabel.Layout.Row = 3;

a1Ticks = sliderTicks(a1Limits,50000);
a1Slider = uislider(controlGrid, ...
    Limits=a1Limits, ...
    Value=a1, ...
    MajorTicks=a1Ticks, ...
    MajorTickLabels=intWithCommas(a1Ticks));
a1Slider.Layout.Row = 4;

a2TitleLabel = uilabel(controlGrid,Text="Price per Square Foot", ...
    FontWeight="bold",FontColor=theme.AreaColor);
a2TitleLabel.Layout.Row = 5;
a2ValueLabel = uilabel(controlGrid,Text="$" + formatWholeNumber(a2) + " per sqft.");
a2ValueLabel.Layout.Row = 6;

a2Ticks = sliderTicks(a2Limits,50);
a2Slider = uislider(controlGrid, ...
    Limits=a2Limits, ...
    Value=a2, ...
    MajorTicks=a2Ticks, ...
    MajorTickLabels=intWithCommas(a2Ticks));
a2Slider.Layout.Row = 7;

a0TitleLabel = uilabel(controlGrid,Text="Base House Price", ...
    FontWeight="bold",FontColor=theme.BasePriceColor);
a0TitleLabel.Layout.Row = 8;
a0ValueLabel = uilabel(controlGrid, ...
    Text="$" + formatWholeNumber(a0) + " base");
a0ValueLabel.Layout.Row = 9;

a0Ticks = sliderTicks(a0Limits,50000);
a0Slider = uislider(controlGrid, ...
    Limits=a0Limits, ...
    Value=a0, ...
    MajorTicks=a0Ticks, ...
    MajorTickLabels=intWithCommas(a0Ticks));
a0Slider.Layout.Row = 10;

equationLabel = uilabel(controlGrid, ...
    Text=currentModelText(a1,a2,a0), ...
    FontWeight="bold", ...
    WordWrap="on");
equationLabel.Layout.Row = 11;

ax = uiaxes(mainGrid);
ax.Layout.Row = 1;
ax.Layout.Column = 2;
ax.Title.String = " House Price Model Visualization";
ax.Title.FontSize = 14;
ax.XLabel.String = "Additional Features (#)";
ax.YLabel.String = "House Area (sqft.)";
ax.ZLabel.String = "Listed Price (USD)";
ax.FontSize = 10;
view(ax,initialView);
grid(ax,"on");
ax.GridAlpha = 0.3;
defaultInteractions = ax.Interactions;

rightPanel = uipanel(mainGrid,Title="Model Controls",FontWeight="bold");
rightPanel.Layout.Row = 1;
rightPanel.Layout.Column = 3;

statsGrid = uigridlayout(rightPanel,[10,1]);
statsGrid.RowHeight = {
    30,...
    30,...
    "fit",...
    "fit",...
    "fit",...
    "fit",...
    "fit",...
    "fit",...
    "fit",...
    "fit"};
statsGrid.Padding = [15 15 15 15];
statsGrid.RowSpacing = 6;

RMSELabel = uilabel(statsGrid,Text="RMSE: $",FontWeight="bold");
RMSELabel.Layout.Row = 1;
SSELabel = uilabel(statsGrid,Text="SSE: ",FontWeight="bold");
SSELabel.Layout.Row = 2;

sepLabel = uilabel(statsGrid,Text="---------------",HorizontalAlignment="center");
sepLabel.Layout.Row = 3;

showOptimalBtn = uibutton(statsGrid,Text="Show Optimal", ...
    BackgroundColor=theme.OptimalButtonColor, ...
    FontColor=theme.OptimalButtonTextColor, ...
    FontWeight="bold", ...
    ButtonPushedFcn=@showOptimalCallback);
showOptimalBtn.Layout.Row = 4;

randomizeBtn = uibutton(statsGrid,Text="Randomize", ...
    BackgroundColor=theme.RandomizeButtonColor, ...
    FontColor=theme.RandomizeButtonTextColor, ...
    FontWeight="bold", ...
    ButtonPushedFcn=@randomizeCallback);
randomizeBtn.Layout.Row = 5;

resetBtn = uibutton(statsGrid,Text="Reset", ...
    BackgroundColor=theme.ResetButtonColor, ...
    FontColor=theme.ResetButtonTextColor, ...
    FontWeight="bold", ...
    ButtonPushedFcn=@resetCallback);
resetBtn.Layout.Row = 6;

visLabel = uilabel(statsGrid,Text="Visualization Options:",FontWeight="bold");
visLabel.Layout.Row = 7;

showResidualsCheck = uicheckbox(statsGrid,Text="Show Residuals", ...
    Value=false,ValueChangedFcn=@(~,~) updateVisualization());
showResidualsCheck.Layout.Row = 8;

showPlaneCheck = uicheckbox(statsGrid,Text="Show Regression Plane", ...
    Value=false,ValueChangedFcn=@(~,~) updateVisualization());
showPlaneCheck.Layout.Row = 9;

rotate3DCheck = uicheckbox(statsGrid,Text="Rotate 3D", ...
    Value=false,ValueChangedFcn=@rotate3DCallback);
rotate3DCheck.Layout.Row = 10;

bottomGrid = uigridlayout(mainGrid,[1,3]);
bottomGrid.Layout.Row = 2;
bottomGrid.Layout.Column = [1 3];
bottomGrid.ColumnWidth = {"1x","fit","fit"};

feedbackLabel = uilabel(bottomGrid, ...
    Text="Adjust the parameters to improve your model fit!", ...
    FontWeight="bold",FontColor=theme.ScoreColor);
feedbackLabel.Layout.Column = 1;

scoreLabel = uilabel(bottomGrid, ...
    Text="Model Score: %", ...
    FontWeight="bold",FontColor=theme.ScoreColor);
scoreLabel.Layout.Column = 2;

congratsLabel = uilabel(bottomGrid, ...
    Text="", ...
    FontWeight="bold",FontColor=theme.SuccessColor);
congratsLabel.Layout.Column = 3;

a1Slider.ValueChangingFcn = @(~,~) sliderCallback();
a2Slider.ValueChangingFcn = @(~,~) sliderCallback();
a0Slider.ValueChangingFcn = @(~,~) sliderCallback();

toggleRotate3D(rotate3DCheck.Value);
drawnow
resetChallenge(a1,a2,a0)

    function sliderCallback(varargin)
        a1ValueLabel.Text = "$" + formatWholeNumber(a1Slider.Value) + " per feature";
        a2ValueLabel.Text = "$" + formatWholeNumber(a2Slider.Value) + " per sqft.";
        a0ValueLabel.Text = "$" + formatWholeNumber(a0Slider.Value) + " base";
        equationLabel.Text = currentModelText(a1Slider.Value,a2Slider.Value,a0Slider.Value);
        updateVisualization();
    end

    function updateVisualization()
        a1Curr = a1Slider.Value;
        a2Curr = a2Slider.Value;
        a0Curr = a0Slider.Value;

        currentView = ax.View;
        delete(ax.Children);
        hold(ax,"off");

        x1Range = linspace(min(x1)-0.2,max(x1)+0.2,30);
        x2Range = linspace(min(x2)-50,max(x2)+50,30);
        [X1Mesh,X2Mesh] = meshgrid(x1Range,x2Range);
        YPredMesh = a1Curr*X1Mesh + a2Curr*X2Mesh + a0Curr;

        if showPlaneCheck.Value
            surf(ax,X1Mesh,X2Mesh,YPredMesh, ...
                FaceAlpha=0.3,FaceColor=theme.SurfaceColor,EdgeColor="none");
            hold(ax,"on");
        end

        yPred = a1Curr*x1 + a2Curr*x2 + a0Curr;
        residuals = y - yPred;

        scatter3(ax,x1,x2,y,60,"filled", ...
            MarkerFaceAlpha=0.9, ...
            MarkerEdgeColor="none", ...
            SeriesIndex=theme.ObservedSeries);
        hold(ax,"on");

        if showResidualsCheck.Value
            for i = 1:length(x1)
                if residuals(i) >= 0
                    residualSeries = theme.PositiveResidualSeries;
                else
                    residualSeries = theme.NegativeResidualSeries;
                end

                plot3(ax, ...
                    [x1(i) x1(i)], ...
                    [x2(i) x2(i)], ...
                    [y(i) yPred(i)], ...
                    SeriesIndex=residualSeries, ...
                    LineWidth=1.5);
            end
        end

        hold(ax,"off");
        ax.View = currentView;

        RMSE = sqrt(mean(residuals.^2));
        SSE = sum(residuals.^2);
        RMSELabel.Text = "RMSE($): " + formatWholeNumber(RMSE);
        SSELabel.Text = "SSE($^2): " + formatWholeNumber(SSE);

        score = scoreFromSSE(SSE);
        scoreLabel.Text = sprintf("Model Score: %.1f%%",score);

        if score > 90
            feedbackLabel.Text = "Excellent fit! You're close to the true model.";
            feedbackLabel.FontColor = theme.SuccessColor;
            congratsLabel.Text = "Nice work.";
        elseif score > 60
            feedbackLabel.Text = "Good fit. Try adjusting parameters slightly.";
            feedbackLabel.FontColor = theme.WarningColor;
            congratsLabel.Text = "";
        else
            feedbackLabel.Text = "Poor fit. Keep tuning the model.";
            feedbackLabel.FontColor = theme.AlertColor;
            congratsLabel.Text = "";
        end

        drawnow limitrate
    end

    function showOptimalCallback(~,~)
        try
            setCoefficients(a1Opt,a2Opt,a0Opt);
        catch ME
            disp(getReport(ME,"extended"))
            uialert(fig,ME.message,"Optimal Button Error");
        end
    end

    function randomizeCallback(~,~)
        [a1Rand,a2Rand,a0Rand] = randomCoefficients();
        setCoefficients(a1Rand,a2Rand,a0Rand);
    end

    function resetCallback(~,~)
        [a1Reset,a2Reset,a0Reset] = randomPoorCoefficients();
        resetChallenge(a1Reset,a2Reset,a0Reset);
    end

    function setCoefficients(a1Value,a2Value,a0Value)
        a1Slider.Value = clampToLimits(a1Value,a1Slider.Limits);
        a2Slider.Value = clampToLimits(a2Value,a2Slider.Limits);
        a0Slider.Value = clampToLimits(a0Value,a0Slider.Limits);
        sliderCallback();
    end

    function resetChallenge(a1Value,a2Value,a0Value)
        referenceSSE = sum((y - (a1Value*x1 + a2Value*x2 + a0Value)).^2);
        referenceSSE = max(referenceSSE,baselineSSE);
        setCoefficients(a1Value,a2Value,a0Value);
    end

    function [a1Rand,a2Rand,a0Rand] = randomCoefficients()
        a1Rand = randRange(a1Limits);
        a2Rand = randRange(a2Limits);
        a0Rand = randRange(a0Limits);
    end

    function [a1Poor,a2Poor,a0Poor] = randomPoorCoefficients()
        worstSSE = -inf;
        worstCoeffs = [a1Limits(1) a2Limits(1) a0Limits(1)];

        for idx = 1:maxPoorFitTries
            [a1Candidate,a2Candidate,a0Candidate] = randomCoefficients();
            candidateResiduals = y - (a1Candidate*x1 + a2Candidate*x2 + a0Candidate);
            candidateSSE = sum(candidateResiduals.^2);

            if candidateSSE > worstSSE
                worstSSE = candidateSSE;
                worstCoeffs = [a1Candidate a2Candidate a0Candidate];
            end
        end

        a1Poor = worstCoeffs(1);
        a2Poor = worstCoeffs(2);
        a0Poor = worstCoeffs(3);
    end

    function score = scoreFromSSE(SSE)
        effectiveSSE = max(SSE,optimalSSE);
        if referenceSSE <= optimalSSE
            score = 100;
            return
        end

        % SSE spans several orders of magnitude, so use a log scale to make
        % intermediate improvements visible instead of collapsing to 0 or 100.
        score = 100 * (log(referenceSSE) - log(effectiveSSE)) / ...
            (log(referenceSSE) - log(optimalSSE));
        score = max(0,min(100,score));
    end

    function rotate3DCallback(src,~)
        toggleRotate3D(src.Value);
    end

    function toggleRotate3D(isEnabled)
        if isEnabled
            ax.Interactions = [rotateInteraction dataTipInteraction];
        else
            ax.Interactions = defaultInteractions;
        end
    end
end

function s = intWithCommas(x)
s = arrayfun(@(v) regexprep(sprintf('%d',v), ...
    '(?<=\d)(?=(\d{3})+$)',','), ...
    x,UniformOutput=false);
end

function v = randRange(lim)
v = lim(1) + diff(lim)*rand();
end

function lim = expandSliderLimits(defaultLimits,targetValue,step)
lowerBound = min(defaultLimits(1),targetValue);
upperBound = max(defaultLimits(2),targetValue);
lim = [step*floor(lowerBound/step), step*ceil(upperBound/step)];
end

function ticks = sliderTicks(lim,step)
ticks = lim(1):step:lim(2);
if ticks(end) ~= lim(2)
    ticks = [ticks lim(2)];
end
ticks = unique(round(ticks));
end

function value = clampToLimits(value,limits)
value = min(max(value,limits(1)),limits(2));
end

function text = currentModelText(a1,a2,a0)
text = "Current Model:" + newline + ...
    "Price = " + formatWholeNumber(a1) + " * Features + " + ...
    formatWholeNumber(a2) + " * Area + " + formatWholeNumber(a0);
end

function text = formatWholeNumber(value)
text = string(regexprep(sprintf("%.0f",value), ...
    '(?<=\d)(?=(\d{3})+$)',','));
end

function theme = houseModelTheme()
palette = orderedcolors("gem");

optimalButtonColor = paletteColor(palette,6);
randomizeButtonColor = paletteColor(palette,3);
resetButtonColor = paletteColor(palette,2);

theme = struct( ...
    "InstructionColor",paletteColor(palette,1), ...
    "FeatureColor",paletteColor(palette,2), ...
    "FeatureValueColor",paletteColor(palette,3), ...
    "AreaColor",paletteColor(palette,4), ...
    "BasePriceColor",paletteColor(palette,5), ...
    "ScoreColor",paletteColor(palette,1), ...
    "SuccessColor",paletteColor(palette,4), ...
    "WarningColor",paletteColor(palette,3), ...
    "AlertColor",paletteColor(palette,2), ...
    "OptimalButtonColor",optimalButtonColor, ...
    "OptimalButtonTextColor",contrastingTextColor(optimalButtonColor), ...
    "RandomizeButtonColor",randomizeButtonColor, ...
    "RandomizeButtonTextColor",contrastingTextColor(randomizeButtonColor), ...
    "ResetButtonColor",resetButtonColor, ...
    "ResetButtonTextColor",contrastingTextColor(resetButtonColor), ...
    "ObservedSeries",1, ...
    "PositiveResidualSeries",2, ...
    "NegativeResidualSeries",5, ...
    "SurfaceColor",paletteColor(palette,6));
end

function color = paletteColor(palette,index)
color = palette(min(index,size(palette,1)),:);
end

function color = contrastingTextColor(backgroundColor)
luminance = 0.2126 * backgroundColor(1) + ...
    0.7152 * backgroundColor(2) + ...
    0.0722 * backgroundColor(3);

if luminance > 0.6
    color = [0 0 0];
else
    color = [1 1 1];
end
end
